//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Army
    {
        public int KingdomId { get; set; }
        public Nullable<int> cEnlisted { get; set; }
        public Nullable<int> cSupport { get; set; }
        public Nullable<int> cRanged { get; set; }
        public Nullable<int> cSpecial { get; set; }
        public Nullable<int> cSiege { get; set; }
        public Nullable<int> cElite { get; set; }
        public Nullable<int> dEnlisted { get; set; }
        public Nullable<int> dSupport { get; set; }
        public Nullable<int> dRanged { get; set; }
        public Nullable<int> dSpecial { get; set; }
        public Nullable<int> dSiege { get; set; }
        public Nullable<int> dElite { get; set; }
        public Nullable<double> Surrender { get; set; }
        public Nullable<int> ArmyClass { get; set; }
    
        public virtual Kingdom Kingdom { get; set; }
    }
}
