//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kingdom
    {
        public int KingdomId { get; set; }
        public Nullable<int> Structures { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<int> Land { get; set; }
        public Nullable<int> Workers { get; set; }
        public Nullable<int> Food { get; set; }
        public Nullable<int> Protection { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Honor { get; set; }
        public string KingdomName { get; set; }
        public Nullable<Conquest.Tax> Taxrate { get; set; }
        public Nullable<int> Continent { get; set; }
        public int PlayerId { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Army Army { get; set; }
        public virtual Vault Vault { get; set; }
    }
}
