//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Kingdom = new HashSet<Kingdom>();
        }
    
        public int PlayerId { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public int Remorts { get; set; }
        public Conquest.Gender Gender { get; set; }
        public Conquest.PlayerClass PlayerClass { get; set; }
        public int CurrentCont { get; set; }
        public int NumAttacks { get; set; }
        public int Movement { get; set; }
    
        public virtual ICollection<Kingdom> Kingdom { get; set; }
    }
}
