//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conquest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vault
    {
        public Vault()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int KingdomId { get; set; }
        public int VaultId { get; set; }
    
        public virtual Kingdom Kingdom { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
